name: naturaDock
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python and core scientific stack
  - python=3.9
  - numpy=1.24.*  # Compatible with most packages
  - pandas>=1.3
  - scipy>=1.7
  - matplotlib>=3.4
  - seaborn>=0.11
  - jupyter>=1.0
  - notebook>=6.4
  
  # Cheminformatics (core packages that actually exist)
  - rdkit=2023.*  # Use older version for compatibility
  - openbabel  # Remove version constraint
  
  # Bioinformatics 
  - biopython>=1.79
  
  # Machine learning and data science
  - scikit-learn>=1.0
  - xgboost>=1.5
  - joblib>=1.1
  
  # Web scraping and APIs
  - requests>=2.26
  - beautifulsoup4>=4.10
  - urllib3>=1.26
  
  # Database and data storage
  - sqlalchemy>=1.4
  - sqlite>=3.36
  
  # Visualization
  - plotly>=5.3
  - bokeh>=2.4
  
  # Parallel processing and utilities
  - dask>=2021.10
  - click>=8.0
  - tqdm>=4.62
  - pyyaml>=6.0
  
  # Development and testing
  - pytest>=6.2
  - black>=21.9
  - flake8>=4.0
  
  # System utilities
  - git>=2.33
  - curl>=7.78
  
  # Pip dependencies for specialized tools
  - pip>=21.3
  - pip:
    - pubchempy>=1.0.4
    - chembl-webresource-client>=0.10.8
    - prody>=2.4.1
    - mdanalysis>=2.0.0
    - biotite>=0.39.0
    - py3dmol>=2.0.4
    - molvs>=0.1.1
    - mordred>=1.2.0
    - streamlit>=1.28.0
    - dash>=2.14.0