name: naturaDock
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python
  - python=3.10

  # Core scientific stack
  - numpy=1.25.2
  - pandas=2.1.0
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=6.4.12

  # Cheminformatics
  - rdkit=2022.09.5
  - openbabel=3.1.1
  - meeko=0.5.0

  # Bioinformatics
  - biopython=1.81
  - pdbfixer=1.11
  - openmm=8.1.1

  # Machine learning and data science
  - scikit-learn=1.3.0
  - xgboost=1.7.3
  - joblib=1.3.2

  # Web scraping and APIs
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - urllib3=1.26.15

  # Database and data storage
  - sqlalchemy=2.0.19
  - sqlite=3.42.0

  # Visualization
  - plotly=5.15.0
  - bokeh=3.2.1
  - py3dmol=2.0.3

  # Parallel processing and utilities
  - dask=2023.7.1
  - click=8.1.7
  - tqdm=4.65.0
  - pyyaml=6.0.1
  - toml=0.10.2
  - openpyxl=3.1.2
  - psutil

  # Development and testing
  - pytest=7.4.3
  - black=23.7.0
  - ruff=0.0.286
  - flake8>=4.0 # ruff replaces flake8, but keeping it for now

  # System utilities
  - git>=2.33
  - curl>=7.78

  # Pip dependencies
  - pip>=21.3
  - pip:
    - pubchempy>=1.0.4
    - chembl-webresource-client>=0.10.8
    - prody>=2.4.1
    - mdanalysis>=2.0.0
    - biotite>=0.39.0
    - molvs>=0.1.1
    - mordred>=1.2.0
    - streamlit>=1.28.0
    - dash>=2.14.0
